### PR TITLE
added Buffered overloads of GetSubscriber, GetPublisher to GlobalMessagePipe

### PR DESCRIPTION
**Pull request by AGeorgy**

### CODE REVIEW

**Comment by NinjaQuinn** [comment]
@AGeorgy I actually could use this, why was it closed instead of merged?

**Comment by quinnhoener** [comment]
@neuecc , wondering your thoughts on getting something like this merged to the main product? I'm not using a 3rd party DI system and want to use buffered messages with the GlobalMessagePipe. 

Thanks!

**Comment by neuecc** [comment]
Yes, ok to merge.
Shall I Reopen and Merge?

**Comment by quinnhoener** [comment]
@neuecc yes please! I couldn't figure out how to do that (maybe I don't have access for that. 

Thank you!

**Comment by quinnhoener** [comment]
Just heads up it looks like this PR might be manually setting the package.json version number. I noticed git history looks like there's a GitHub Action tied to incrementing that number across all the packages?

**Comment by neuecc** [comment]
For now, let's get it out with 1.7.4.

**Comment by quinnhoener** [comment]
Thanks for this! Greatly appreciate the quick turnaround.

**Pull request merged**
